# -*- coding: utf-8 -*-
"""area_retirada_pinus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njmwDUgEzk1uTNmJKWDKhpubYUdROJvB
"""

!pip install xarray
!pip install xee

import ee
import xarray as xr
import xee
from xee import helpers
import shapely.geometry
import geemap

ee.Authenticate()
ee.Initialize(project='ee-marciobcure', opt_url='https://earthengine-highvolume.googleapis.com')

#map = geemap.Map(basemap = 'SATELLITE')
#map

#roi = map.draw_last_feature.geometry()
#roi

shapely_aoi = shapely.geometry.Polygon([
    [-48.44113, -27.541838],
    [-48.44113, -27.528291],
    [-48.425427, -27.528291],
    [-48.425427, -27.541838],
    [-48.44113, -27.541838]
])

# Função para mascarar nuvens e aplicar o fator de escala
def mask_and_scale_s2(image):
    qa = image.select('QA60')

    cloud_bit_mask = 1 << 10
    cirrus_bit_mask = 1 << 11

    mask = qa.bitwiseAnd(cloud_bit_mask).eq(0).And(
           qa.bitwiseAnd(cirrus_bit_mask).eq(0))

    scaled_bands = image.select(['B4', 'B8']).multiply(0.0001)

    return image.addBands(scaled_bands, overwrite=True).updateMask(mask).copyProperties(image, image.propertyNames())

# Função para calcular o EVI2
def calculate_evi2(image):
  red = image.select('B4')
  nir = image.select('B8')

  evi2 = image.expression(
        '2.5 * ((NIR - RED) / (NIR + 2.4 * RED + 1))',
        {
            'NIR': nir,
            'RED': red
        }).rename('EVI2')
  return image.addBands(evi2)

# Configuração para xarray.open_dataset com xee
# Definir a projeção e escala desejadas para o download
target_crs = 'EPSG:3857'   # Web Mercator, unidades = metros
scale = 10                 # metros por pixel

print("Preparando para abrir o dataset com xarray e xee...")

# Este bloco de código só será executado se o Earth Engine estiver inicializado.
# No seu ambiente local, após ee.Initialize(), esta parte funcionará.
if ee.data.is_initialized():
    # Definir ee_roi aqui, pois requer a inicialização do Earth Engine
    ee_roi = ee.Geometry.Polygon(
        [[[-48.44113, -27.541838],
[-48.44113, -27.528291],
[-48.425427, -27.528291],
[-48.425427, -27.541838],
[-48.44113, -27.541838]]])

# Carregar e processar a coleção Sentinel-2
s2_collection = ee.ImageCollection("COPERNICUS/S2_HARMONIZED")\
        .filterDate('2025-12-01', '2026-06-28')\
        .filterBounds(ee_roi)\
        .map(mask_and_scale_s2)\
        .map(calculate_evi2)\
        .select('EVI2')

count = s2_collection.size().getInfo()
if count == 0:
        print("A coleção de imagens está vazia para a ROI e período especificados.")
        print("Por favor, verifique a ROI e as datas.")
else:
        print(f"Coleção de imagens contém {count} imagens. Abrindo com xarray...")
        try:
            # Usar helpers.fit_geometry para gerar os parâmetros de grade
            grid_params = helpers.fit_geometry(
                geometry=shapely_aoi,
                grid_crs=target_crs,
                grid_scale=(scale, -scale) # xee espera uma tupla (x_scale, y_scale), y_scale é negativo para origem superior esquerda
            )

            ds = xr.open_dataset(
                s2_collection,
                engine='ee',
                **grid_params # Passar os parâmetros de grade usando o operador **
            )
            print("Dataset Xarray criado com sucesso!")
            print(ds)

            # Exemplo de como acessar os dados (isso pode acionar o download)
            # print("Primeira imagem do EVI2:\n", ds['EVI2'].isel(time=0).values)

        except Exception as e:
            print(f"Erro ao abrir o dataset com xarray e xee: {e}")
            print("Verifique se a sua ROI está dentro de uma área com dados Sentinel-2 e se a inicialização do EE está correta.")
        else:
            print("Earth Engine não inicializado. Por favor, descomente e execute ee.Authenticate() e ee.Initialize() no seu ambiente local.")

print("Processo concluído.")

monthly = ds.resample(time='ME').mean('time')

monthly

monthly.EVI2.plot(col = 'time', col_wrap = 4, robust = True, cmap = "RdYlGn", vmin = 0, vmax = 0.5)

ds.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))

ds['EVI2'].isel(time=9).plot(
    cmap='RdYlGn',
    vmin=-.2,
    vmax=.6
)

plt.title("EVI2 - Pinus")
plt.show()

!pip install plotnine[extra]

import plotnine as p9

import pandas as pd

#df = pd.DataFrame(ds.EVI2.isel(time=11).values.flatten(), columns=['EVI2'])
df = ds.to_dataframe().reset_index()
df.head()

p9.ggplot(
    df[(df['x'] == -5392245.0) & (df['y'] == -3189635.0)],
    p9.aes(x='time', y = 'EVI2')) + p9.geom_line()